[book]
title = "3D Printing Course for Blind and Visually Impaired Learners"
authors = ["Michael Ryan Hunsaker, M.Ed., Ph.D."]
language = "en"
description = "An introduction to 3D printing for blind and visually impaired learners, using OpenSCAD and 3DMake to create accessible 3D models."
src = "src"

[output.html]
additional-css = ["src/assets/custom.css"]
default-theme = "rust"
site-url = "https://github.com/mrhunsaker/VI_3DMake_OpenSCAD_Curriculum"
theme = "theme"

[build]
build-dir = "docs"
create-missing = true
use-default-preprocessors = true

# Enables the search feature
[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

# Fold sections in the sidebar by default for easier navigation
[output.html.fold]
enable = true
level = 1

[preprocessor.index]
[preprocessor.links]
