[book]
title = "3D Printing Course for Blind and Visually Impaired Learners"
authors = ["Michael Ryan Hunsaker, M.Ed., Ph.D."]
language = "en"
description = "An introduction to 3D printing for blind and visually impaired learners, using OpenSCAD and 3DMake to create accessible 3D models."
src = "src"

[preprocessor.index]
[preprocessor.links]

[build]
build-dir = "docs"
create-missing = true
use-default-preprocessors = true

[output.html]
additional-css = ["src/assets/custom.css"]
default-theme = "rust"
site-url = "https://github.com/mrhunsaker/VI_3DMake_OpenSCAD_Curriculum"
theme = "theme"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.fold]
enable = true
level = 1

[output.pandoc]
[output.pandoc.profile.pdf]
output-file = "OpenSCAD_Curriculum.pdf"
to = "latex"
number-sections = false
toc = true
toc-depth = 3
include-before-body = ["src/Cover.tex"]
template = "src/template.tex"
pdf-engine = "lualatex"
filters = ["src/code-to-listings.lua"]

[output.pandoc.profile.pdf.variables]
listings = true  
secnumdepth = 2
date = "2026-02-24"
title-meta = "3D Printing Course for Blind and Visually Impaired Learners"
author-meta = "Michael Ryan Hunsaker, M.Ed., Ph.D."
title = ""
author = ""
documentclass = "book"
papersize = "letter"
fontsize = "11pt"
maketitle = false
header-includes = "\\usepackage{url}"

[output.pandoc.profile.epub]
output-file = "OpenSCAD_Curriculum.epub"
to = "epub"
number-sections = false
toc-depth = 3
include-before-body = ["src/Cover.html"]

[output.pandoc.profile.epub.variables]
date = "2026-02-24"
title-meta = "3D Printing Course for Blind and Visually Impaired Learners"
author-meta = "Michael Ryan Hunsaker, M.Ed., Ph.D."

[output.pandoc.profile.latex]
output-file = "OpenSCAD_Curriculum.tex"
to = "latex"
number-sections = false
toc-depth = 3
include-before-body = ["src/Cover.tex"]
template = "src/template.tex"
filters = ["src/code-to-listings.lua"]

[output.pandoc.profile.latex.variables]
date = "2026-02-24"
title-meta = "3D Printing Course for Blind and Visually Impaired Learners"
author-meta = "Michael Ryan Hunsaker, M.Ed., Ph.D."